sudo: false
language: perl
env: PERL_CPANM_OPT=\"--notest --force --skip-satisfied\"
perl:
   - '5.22'

before_install:
  - pip install --user htseq

addons:
  apt:
    packages:
    - samtools
    - liblzma-dev
    - libbam-dev
    - python-numpy
