language: perl
perl:
  - "5.22"

sudo: false

addons:
  apt:
    packages:
      - samtools
      - bowtie
      - python-htseq
      - ncbi-blast+
      - curl

install:
  - "cpanm XML::SAX XML::SAX::Writer XML::Simple 2>&1"
  - "perl Makefile.PL && make && make install"

script:
  - make test

notifications:
  email: false
