language: perl
perl:
  - "5.22"

before_install:
  - sudo apt-get -qq update && apt-cache search tophat
##  - sudo apt-get install -y samtools tophat bowtie bowtie2 python-htseq trimmomatic fastqc ncbi-blast+ curl

script:
  - make test

notifications:
  email: false
