language: perl
perl:
  - "5.22"

before_install:
  - sudo apt-get update
  - apt-cache search samtools
  - apt-cache search bowtie
  - apt-cache search python-htseq
  - sudo apt-get install -y samtools bowtie ncbi-blast+ curl
## maybe change these for tophat and friends
##  - wget http://pngquant.org/pngquant_1.7.1-1_i386.deb
##  - sudo dpkg -i pngquant_1.7.1-1_i386.deb

script:
  - make test

notifications:
  email: false
