sudo: false
language: perl
env: PERL_CPANM_OPT=\"--notest --force --skip-satisfied\"
perl:
   - '5.24'

addons:
  apt:
    packages:
    - samtools
    - liblzma-dev
    - libbam-dev
    - python-numpy
    - bowtie2
    - bwa
    - tophat
    - libbio-samtools-perl

before_install:
  - pip install --user htseq

cache:
  timeout: 3000
  packages: true

notifications:
  email: false
