language: perl
env: PERL_CPANM_OPT=\"--notest --force --skip-satisfied\"
perl:
   - '5.22'

before_install:
  - sudo apt-get update -qq
  - sudo apt-get -y install libhts1 libhts-dev samtools liblzma-dev libbam-dev python-numpy python-htseq

