sudo: false
language: perl

cache:
  bundler: true
  directories:
    - /home/travis/perl5

perl:
    - "5.26"

addons:
  apt:
    packages:
    - samtools
    - liblzma-dev
    - libbam-dev
    - python-numpy
    - bowtie2
    - bwa
    - tophat
    - libbio-samtools-perl
    - libbam-dev
    - fastqc
    - bowtie
    - trimmomatic
    - python-htseq
    - xz-utils

script:
  - make Makefile.PL && make && make install && make test


notifications:
  email: false

env:
  global:
    - SAMTOOLS="/usr/include/samtools"
    - LESSOPEN="/usr/bin/lessfile %s"
    - PERL_CPANM_OPT="--notest --force --skip-satisfied"
